version: "3"
x-airflow-common:
  &airflow-common
  image: apache/airflow:2.9.2
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__WEBSERVER__RBAC: "true"
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
    AIRFLOW__CORE__FERNET_KEY: "a_very_secret_fernet_key"
    _PIP_ADDITIONAL_REQUIREMENTS: "-r /requirements/requirements.txt"
  volumes:
    - ./dags:/opt/airflow/dags
    - ./plugins:/opt/airflow/plugins
    - ./requirements.txt:/requirements/requirements.txt
    - ../dbt_project:/opt/airflow/dbt_project
    - ../data:/opt/airflow/data
  user: "50000:0"
  depends_on:
    - postgres

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports: ["5432:5432"]

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports: ["8080:8080"]

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler

  airflow-init:
    <<: *airflow-common
    command: bash -c "airflow db init && airflow users create --username admin --password admin --firstname a --lastname b --role Admin --email admin@example.com"
